business_ideas_upm/business_ideas_upm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("ideas.urls")),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

business_ideas_upm/ideas/urls.py
from django.urls import include, path

from . import views


app_name = "ideas"

urlpatterns = [
    path("", views.list, name="index"),
    path("list", views.list, name="list"),
    path("idea/<int:idea_id>", views.idea, name="idea"),
    path("idea_new", views.idea_new, name="idea_new"),
    path("idea_new_post", views.idea_new_post, name="idea_new_POST")
]

business_ideas_upm/polls/urls.py
from django.urls import path

from . import views


app_name = "pauls"

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

business_ideas_upm/ideas/models.py
from sqlite3 import Date
from django.db import models

# Create your models here.
class BusinessIdea(models.Model):
    title = models.TextField(max_length=128)
    body = models.TextField(max_length=4096)
    username = models.TextField(max_length=32)
    publish_date = models.DateTimeField()


class IdeaComment(models.Model):
    idea = models.ForeignKey(BusinessIdea, on_delete=models.CASCADE)
    body = models.TextField(max_length=4096)
    username = models.TextField(max_length=32)
    publish_date = models.DateTimeField()

business_ideas_upm/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return "Q"+str(self.question.id)+": "+self.choice_text

business_ideas_upm/ideas/views.py
from datetime import datetime
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse

from .models import BusinessIdea

# Create your views here.

def list(request):
    ideas_list = BusinessIdea.objects.order_by("-publish_date")[:10]
    template = loader.get_template('ideas/list.html')
    context = {
        'ideas_list': ideas_list,
    }
    return HttpResponse(template.render(context, request))


def idea(request, idea_id):
    try:
        idea = BusinessIdea.objects.get (pk=idea_id)
    except BusinessIdea.DoesNotExist:
        raise Http404("Idea does not exist")
    
    #comments = IdeaComment.objects.filter()
    print(idea.__dir__())
    return render(request, 'ideas/detail.html', {"idea": idea, "comments": ""})


def idea_new(request):
    return render(request, "ideas/idea_new.html")


def idea_new_post(request):
    print(request.POST.keys())
    try:
        username = request.POST['username']
        title = request.POST["title"]
        body = request.POST["body"]
    except (KeyError):
        # Redisplay the form.
        return render(request, 'ideas/idea_new.html', {
            'error_message': "Invalid form.",
        })
    
    newIdea = BusinessIdea(
        username = username,
        title = title,
        body = body,
        publish_date = datetime.now() 
    )
    newIdea.save()
    context = {
        "idea": newIdea
    }
    return HttpResponseRedirect(reverse("ideas:idea", args=(newIdea.id,)))

business_ideas_upm/polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('pauls:results', args=(question.id,)))

business_ideas_upm/ideas/templates/ideas/detail.html
<a href="{% url 'ideas:list' %}" class="button">Return to list</a><br>

<fieldset>
    <h1>{{ idea.title }}</h1>
    <label>{{ idea.publish_date }}</label>
    <label>{{ idea.username }}</label>

    <p>{{ idea.body }}</p>
</fieldset>
<fieldset>
    {% for comment in idea.ideacomment_set.all %}
        <fieldset>
            <label>{{ comment.publish_date }}</label> <label>{{ comment.username }}</label> 
            <p>{{ comment.body }}</p>
        </fieldset>
    {% endfor %}
</fieldset>

business_ideas_upm/ideas/templates/ideas/idea_new.html
<a href="{% url 'ideas:list' %}" class="button">Return to list</a><br>

<form action="{% url 'ideas:idea_new_POST' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Post a new idea</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label>Username</label><br>
            <input type="text" name="username" value=""><br>
            <label>Title</label><br>
            <input type="text" name="title" value=""><br>
            <label>Detailed description of the idea</label><br>
            <textarea name="body" rows="4" cols="50"></textarea><br>
    </fieldset>
    <input type="submit" value="Submit my idea">
</form>

business_ideas_upm/ideas/templates/ideas/list.html
<a href="{% url 'ideas:idea_new' %}" class="button">+ New idea</a>
{% if ideas_list %}
    <ul>
    {% for idea in ideas_list %}
        <li><a href="{% url 'ideas:idea' idea.id %}">{{ idea.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No business ideas are available.</p>
{% endif %}

business_ideas_upm/polls/templates/polls/detail.html
<form action="{% url 'pauls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

business_ideas_upm/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'pauls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

business_ideas_upm/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pauls:detail' question.id %}">Vote again?</a>